### ISSUE TITLE
Input: Doctoral thesis (not Doctorate thesis) is the correct term

### ISSUE THREAD

**Issue by agnepagne** [KTH-Library/bibliomatrix#101]
Seems like a fairly easy change, though we might have to think a little about exactly where to change.

**Comment by agnepagne** [comment]
Usually the best place to fix a data problem is at the source. Does this come from the SAS runs or from DiVA or from somewhere else?

**Comment by mskyttner** [comment]
@agnepagne should this be included in the next milestone?

**Comment by agnepagne** [comment]
I have not found where "Doktorsavhandling" from DiVA is translated to "Doctorate thesis".
We could substitute in the ABM code, but better to fix at the source.

@fileunderwater, do you know where the pt_new field is created?

**Comment by agnepagne** [comment]
The source of "Doctorate" is identified, it is in the script that creates the BIBSTAT.dbo.DiVA_rev table (which among other things translate Swedish DiVA document types to English).

**Comment by agnepagne** [comment]
Fixed in 9ec300ecb1bb8b6c2f6c9ce68a89aa92cd89e721
