### ISSUE TITLE
OA-tab: Aspect ratio in the mobile variant of the pie chart needs trimming in the left margin

### ISSUE THREAD

**Issue by gaeldubus** [KTH-Library/bibliomatrix#107]
Cf. [this comment](https://github.com/KTH-Library/bibliomatrix/pull/106#pullrequestreview-381114416) in #106 

> Would it be possible to trim the aspect ratio a little bit in the mobile variant of the pie chart? It looks like it would be able to fit if the white padding was trimmed in the left margin of the pie, see example screenshot here:
> 
> ![oa-iphone678](https://user-images.githubusercontent.com/1715840/77538059-66b1b880-6e9f-11ea-864f-b77cff895671.png)

Related to #86

**Comment by agnepagne** [comment]
Pie chart replaced.
