### ISSUE TITLE
GitHub Action R CMD check warnings/errors need fixing

### ISSUE THREAD

**Issue by mskyttner** [KTH-Library/bibliomatrix#125]
While the Travis build seem to complete for the same code (see https://travis-ci.org/github/KTH-Library/bibliomatrix/builds), it looks like the gh action (adapted for not building the vignettes in "check" and "build" steps) complains about a number of things.

For example, it requires files to be present corresponding to vignettes, in the inst/doc location, but cannot find those files since they're there, see https://github.com/KTH-Library/bibliomatrix/tree/bugfixes/inst/doc...

**Comment by agnepagne** [comment]
Is it reasonable to try adding `--ignore_vignettes` to `args` in `rcmdcheck`?

**Comment by mskyttner** [comment]
Fixed in 73468840085243cc9e69a0aaa846f758d972c4b1
