### ISSUE TITLE
Some notes etc from R CMD check to fix

### ISSUE THREAD

**Issue by mskyttner** [KTH-Library/bibliomatrix#188]
Namespaces in Imports field not imported from:
  'RColorBrewer' 'curl' 'dbplyr' 'here' 'httr' 'openssl' 'shinythemes'
  All declared Imports should be used.
Unexported object imported by a ':::' call: 'flexdashboard:::html_dependencies_fonts'
  See the note in ?`:::` about the use of this operator.
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
abm_ui_button_publist: no visible binding for global variable 'Ptop5'
abm_ui_button_publist: no visible binding for global variable 'Cf_log'
mean_indicator_units: no visible binding for global variable 'Cf_log'
mean_indicator_units: no visible binding for global variable 'Ptop5'
mean_indicator_units: no visible binding for global variable 'Ptop25'
Undefined global functions or variables:
  Cf_log Ptop25 Ptop5

**Comment by agnepagne** [comment]
Unimported ':::' call fixed in https://github.com/KTH-Library/bibliomatrix/commit/aa914100d7705247f6ee395ae45c7e533586985e

```
> rmark <- list(rmarkdown::html_dependency_font_awesome())
> flexd <- flexdashboard:::html_dependencies_fonts(TRUE, FALSE)
> identical(rmark, flexd)
[1] TRUE
```

**Comment by agnepagne** [comment]
Merged
