### ISSUE TITLE
Scrollbar shown in SDG-tables

### ISSUE THREAD

**Issue by fileunderwater** [KTH-Library/bibliomatrix#196]
Unneccesary, and the full (small) table isn't shown

![bild](https://user-images.githubusercontent.com/1737336/203279970-58bc4a6b-0f67-41fc-83f6-faadd3d07552.png)

**Comment by mskyttner** [comment]
When using DT 0.26, flexdashboard 0.6.0 and rmarkdown 2.18, the table on the right shows 9 rows and a small scrollbar.

![image](https://user-images.githubusercontent.com/1715840/203289896-e854d715-e825-4b14-9d11-908c251acd88.png)
