### ISSUE TITLE
Placement/sizing of top-row tables wrong in cit-impact and SDG

### ISSUE THREAD

**Issue by fileunderwater** [KTH-Library/bibliomatrix#197]
The left table is too large and is pushing the right table out of view (the right one is to large as well)

![bild](https://user-images.githubusercontent.com/1737336/203280358-5dd61ee8-5a65-4e22-be0e-9e95d0640ef9.png)

![bild](https://user-images.githubusercontent.com/1737336/203280487-c9890fd6-089a-47bf-a3b0-8ae054399c35.png)

**Comment by mskyttner** [comment]
For Citation impact "page"/tab, when using DT 0.26, flexdashboard 0.6.0 and rmarkdown 2.18:

![image](https://user-images.githubusercontent.com/1715840/203290503-5dad5d1c-5471-4ebe-8134-05b1ad212809.png)
