### ISSUE TITLE
The abm tests throw some warnings

### ISSUE THREAD

**Issue by mskyttner** [KTH-Library/bibliomatrix#20]
There are some warnings thrown by the abm tests, it would be nice to get rid of those if possible.

```
test-abm.R:45: warning: cf-test
`lang_name()` is deprecated as of rlang 0.2.0.
Please use `call_name()` instead.
This warning is displayed once per session.

test-abm.R:45: warning: cf-test
`lang()` is deprecated as of rlang 0.2.0.
Please use `call2()` instead.
This warning is displayed once per session.

test-abm.R:45: warning: cf-test
Missing values are always removed in SQL.
Use `MAX(x, na.rm = TRUE)` to silence this warning
This warning is displayed only once per session.

test-abm.R:45: warning: cf-test
binding factor and character vector, coercing into character vector

test-abm.R:45: warning: cf-test
binding character and factor vector, coercing into character vector

test-abm.R:75: warning: jcf-test
binding factor and character vector, coercing into character vector

test-abm.R:75: warning: jcf-test
binding character and factor vector, coercing into character vector

test-abm.R:89: warning: co-pub test
binding factor and character vector, coercing into character vector

test-abm.R:89: warning: co-pub test
binding character and factor vector, coercing into character vector
```

**Comment by agnepagne** [comment]
The "binding factor and character vector" warnings come from the sliding_interval function returning a factor for the interval column. This is an easy fix.

**Comment by fileunderwater** [comment]
@agnepagne @mskyttner Is this issue resolved? I’m getting similar warnings in the flexdashboard-branch, also after pulling current master into the branch

**Comment by agnepagne** [comment]
We decided not to do anything about the `lang_name()`  and `lang()` problem at this point. The other warnings should be gone.

**Comment by fileunderwater** [comment]
Yes, I noticed the comment in the other pull request after I write this (about potential upstream problems). Seems better to leave it. @agnepagne

**Comment by mskyttner** [comment]
Things seem to be happening related to this issue "upstream" in dbplyr and when dbplyr 2.0 is released it will likely get fixed:

https://github.com/tidyverse/dbplyr/commit/9c7442e0fbbdc5bd266712c0df5c4fe627808a86
https://github.com/tidyverse/dbplyr/milestone/4
https://github.com/tidyverse/dbplyr/issues/375#issuecomment-565579481

**Comment by agnepagne** [comment]
Now that dbplyr is updated and no longer use the deprecated functions, this is not a problem for us anymore.
