### ISSUE TITLE
Test fails when getting private data for specific kthid

### ISSUE THREAD

**Issue by mskyttner** [KTH-Library/bibliomatrix#24]
This test fails when the last kthid in the list is added:

https://github.com/KTH-Library/bibliomatrix/blob/master/tests/testthat/test-abm-private-data.R#L19

It could be related to users with few data records and the `sliding_intervals()` function.

**Comment by agnepagne** [comment]
The abm_tables* functions that rely on `sliding_intervals()` now check if the unit has any data at all. If not, a single row with Interval = "Total" and everything else = `NA` is returned.

However, I think this will still fail if the difference between the first and last observed year is less than two.

**Comment by agnepagne** [comment]
It seems like sliding_intervals() works even if the given unit code has only one or two years with publications, so functions will not break. But a related problem comes up when the smallest year with publications is near the beginning or end of the "allowed" interval, for example 2017. Then intervals are created for 2015-2017, 2016-2018 and 2017-2019.

A problem here is that abm_table functions are not aware of the year limits (in ABM 2019 this is 2012-2018). This has other implications as well - for example abm_table3 filters out publications with publication_year < max(publication_year) which is only correct if the unit_code has publications 2018.
