### ISSUE TITLE
Create graphs for use in ABM

### ISSUE THREAD

**Issue by agnepagne** [KTH-Library/bibliomatrix#25]
Some elements that have been discussed are
- a graph with cf and top10_share (floating intervals, like in table3)
- a graph with jcf and top20_share (floating intervals, like in table4)
- bullet graphs (and possibly waffle graphs for shares) for the dashboard indicators.

**Comment by agnepagne** [comment]
Nice ggplot bullet graph example: https://github.com/hrbrmstr/Rbulletgraph

**Comment by fileunderwater** [comment]
@agnepagne Notice that I added some crude placeholder graphs in #26 , so this should build on/replace those.

**Comment by agnepagne** [comment]
@fileunderwater nice, then I'll wait for #26 to be merged and start from there.

**Comment by fileunderwater** [comment]
@agnepagne There is an open pull request now.
