### ISSUE TITLE
Use number formatting instead of rounding when presenting tables

### ISSUE THREAD

**Issue by fileunderwater** [KTH-Library/bibliomatrix#27]
Modify presentation in flexdashboard so that tables are presented with a set number of decimals and some values formatted as percentage (e.g. WoS coverage), but not rounded values. The rounded input causes the graphs based on those tables to look more stepwise than they really are.

**Comment by agnepagne** [comment]
Removed the general rounding of df:s in the abm_graphs branch. I think that branch is a good place to do this, since removing rounding affects both graphs and tables. Also adjusted table 1 (field names and number formats).
