### ISSUE TITLE
Getting data in abm.Rmd for summary indicators fails for org units with low number of records

### ISSUE THREAD

**Issue by mskyttner** [KTH-Library/bibliomatrix#30]
Code such as:

`avg_cf <- as.numeric(df_cf[4,"cf"]) %>% round(digits=2)`

hard codes the row number but results may not always have say 4 rows.

Should we use abm_dash_indices() or refactored to use tables that are already fetched with another function?

**Comment by agnepagne** [comment]
This is a smaller problem in PR #28, where code for dashboard indicators uses `nth(..., -2)` for second to last row (which is last row that is not "Total").

Will still fail if the data frame is empty, but this is unlikely for non-individual units.

**Comment by agnepagne** [comment]
Dashboard firstpage in #28 now prints "No data" if it can't find data for the chart.
