### ISSUE TITLE
Graphs on overview with strange scaling on Windows

### ISSUE THREAD

**Issue by fileunderwater** [KTH-Library/bibliomatrix#47]
At least on windows, the scaling of bullet graphs on the overview page is strange, with extremely small graphs.

![flexdashboard_scaling](https://user-images.githubusercontent.com/1737336/70808064-2e3e1100-1dbf-11ea-9d57-df156d48ca32.png)

**Comment by agnepagne** [comment]
This is odd, the overview looks "normal" on my Windows. If I remove `{data-height=240}` from the first Row in Overview, I get a "squashed" look with minimal charts similar to this. What happens if you fiddle with data-heigt, @fileunderwater, like set it to 480 or so?

**Comment by fileunderwater** [comment]
I’ve haven’t tried changing data-heigut, but from your description this seems to be the reason. I’ll try and get back to you. Either way, case this is not critical to fix quickly

**Comment by fileunderwater** [comment]
Problem gone after local R upgrade + package upgrades, so this is not relevant at the moment. Very hard to reproduce now though (I don't know exactly what caused this). I'm closing this for now.
