### ISSUE TITLE
Obsolete stuff in documentation

### ISSUE THREAD

**Issue by agnepagne** [KTH-Library/bibliomatrix#48]
Much of the information in https://kth-library.github.io/bibliomatrix/ is based on data_bibmon.R, which is obsolete. We should remove data_bibmon.R and update documentation to reflect current functionality.

**Comment by agnepagne** [comment]
Files to update:
- README.Rmd
- vignettes/intro.Rmd
- doc/intro.Rmd (seems identical to the one in vignettes, which one to update?)
- more?

**Comment by fileunderwater** [comment]
@agnepagne About the doc/intro.Rmd; the same file is also found in inst/doc, but this is the one that is copied recursively from /doc in dev.R (if I remember correctly)

**Comment by agnepagne** [comment]
@fileunderwater After reading `?devtools::build_vignettes` I am quite sure that vignettes/intro.Rmd is copied into doc/ when we run build_vignettes. And you remember correctly, this file is later copied into inst/doc as the last step in dev.R.

Maybe some day we can draw a couple of flow charts over how files and data are transported through the system, what triggers which event and in which order and so on.
