### ISSUE TITLE
Missing font error message

### ISSUE THREAD

**Issue by mskyttner** [KTH-Library/bibliomatrix#52]
The API when run on clean container complains about missing Arial font:

```
api_1         | Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y,  :
api_1         |   font family 'Arial' not found in PostScript font database
```

We may need to install any required fonts.

**Comment by agnepagne** [comment]
In addition to above warning (a lot of times per request) I get below warning when I run on my local Windows. I guess it's related.

Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database

**Comment by mskyttner** [comment]
I think Arial is a MS font and not open source thus not included on *nix, but can be installed with ttf-mscorefonts-installer package. I have seen LiberationSans being used instead, comes pre-installed. Is even Arial one of the fonts recommended in the web graphical profile for KTH? I thought it was Georgia and Open Sans?

**Comment by mskyttner** [comment]
I think something like this can be used to install missing fonts to be used from R:

https://github.com/KTH-Library/ktheme/blob/master/R/font-open-sans.R#L18

If using Arial, the Arial Narrow variant may be preferable (but Open Sans / Georgia even more so because the KTH Graphical Profile recommends that). The reason for why Arial Narrow might be a better choice than Arial is described here: https://github.com/hrbrmstr/hrbrthemes/blob/master/README.Rmd#L25

In `ktheme` the Open Sans is used, it has a Narrow variant (https://www.fontsquirrel.com/fonts/open-sans-condensed), but I'm not sure it would "comply" with the KTH Graphical Profile.

**Comment by agnepagne** [comment]
Changed "Arial" to "sans" in PR #51 (the cleanup one) as a temporary fix just to get rid of the error messages. I **think** it should work on all platforms.
