### ISSUE TITLE
Consistent organization order

### ISSUE THREAD

**Issue by agnepagne** [KTH-Library/bibliomatrix#55]
@mskyttner, is there any logic in how the dropdown in the ABM shiny app shows the order of schools and departments? To avoid confusion, I guess alphabetical order is best.

**Comment by mskyttner** [comment]
It is a depth first search: https://github.com/KTH-Library/bibliomatrix/blob/master/R/abm.R#L422 which is making use of this https://rdrr.io/cran/igraph/man/dfs.html and I'm not sure how incoming node order is respected by the dfs across different levels of the tree. If the dfs algo doesn't reorder in-level existing ordering, it could be added in addition to the existing ordering which is defined here: https://github.com/KTH-Library/bibliomatrix/blob/master/R/abm.R#L395

**Comment by agnepagne** [comment]
Yes, adding `unit_long_en` to `arrange` seems at least partly helpful, thank you @mskyttner! Order within school is preserved, order between schools is not.
