### ISSUE TITLE
Too much unnecessary in sqlite db

### ISSUE THREAD

**Issue by agnepagne** [KTH-Library/bibliomatrix#56]
By default, db_sync() will fetch all tables in BIBMON except Document. There are other tables, like DIVA_School_dept, with old not very useful data, and Bestresaddr_KTH which is large and quite useless without Document.

**Comment by mskyttner** [comment]
The db_sync() fcn could take a default set of "included" to target the most relevant tables like the "excluded" param does in that fcn?

**Comment by agnepagne** [comment]
Hm, maybe we should extend the default "excluded" list instead. Depends if we want to, by default, sync the (many) small tables that we use for testing SAS output against R output.

**Comment by mskyttner** [comment]
@agnepagne after syncing with `db_sync()` just now, the size on disk for the sqlitedb is 233M, which is not huge. So we may not be too worried about space. But if we wanted to exclude tables (beyond the bigger Documents table, by default), what should be excluded? Bestresaddr_KTH, too, for now?

**Comment by agnepagne** [comment]
OK, I won't worry about space @mskyttner. :) It's not like `db_sync()` takes ages to run either. If/when we decide to clean up, I guess the most obvious (and large:ish) tables to exclude would be Bestresaddr_KTH, DIVA_School__dept, Diva_departments and Doc_statistics. Neither of them are used atm.

**Comment by agnepagne** [comment]
Down to 113M when the mentioned tables are excluded.

**Comment by mskyttner** [comment]
Good! :+1:

**Comment by agnepagne** [comment]
Closed to early, wait until PR is merged.

**Comment by agnepagne** [comment]
Fixed in #51
