### ISSUE TITLE
Update .Rbuildignore and .gitignore to not include any .html from inst/extdata

### ISSUE THREAD

**Issue by mskyttner** [KTH-Library/bibliomatrix#59]

**Comment by agnepagne** [comment]
Also excluding .html from inst/shiny-apps/abm/www 38b64abec7a7f2e7ceffa217fbef1c819462cf45

Specifically excluding `[0-9]+` and `[0-9a-f]{32}` would require an awkward .gitignore file, since .gitignore does not support regexp.

**Comment by agnepagne** [comment]
On the other hand, I am an awkward guy. 8a34469a78b8dcbb7af51ee13be8b09ba5ff4ad1
Now excluding only .html files with names constisting of 3-8 decimal digits or exactly 32 hexadecimal digits.

**Comment by mskyttner** [comment]
:) maybe we should introduce this convention: any files in the www/cache directory gets ignored? I could then change the app since I'm working on it now anyways.

**Comment by agnepagne** [comment]
That seems like a less awkward but far better idea, @mskyttner! :)

**Comment by agnepagne** [comment]
Fixed in #51
