### ISSUE TITLE
Mobile layout: Legends get cropped for some graphs on small displays

### ISSUE THREAD

**Issue by mskyttner** [KTH-Library/bibliomatrix#70]
This issue could use a screenshot if possible. Not sure if fully relevant, but could perhaps be adressed by a) .{mobile} c) ggplotify / plot_ly-wrapping of graphs?

**Comment by agnepagne** [comment]
För screenshot, se [trellokortet](https://trello.com/c/lbcJVJw8).

**Comment by mskyttner** [comment]
This issue seems to come from .mobile graphs getting rendered with a smaller viewport, the issue has been adressed in #83
