### ISSUE TITLE
Default organizational unit in the app should be KTH, not the logged in researcher/employee

### ISSUE THREAD

**Issue by mskyttner** [KTH-Library/bibliomatrix#94]
The suggestion is to set the initial selected dropdown index to the second entry in the list while keeping the researcher as the first entry in the organizational unit dropdown.

**Comment by agnepagne** [comment]
Preselected org set to KTH in #95

**Comment by mskyttner** [comment]
Reverted due to changes in PR #99

**Comment by mskyttner** [comment]
These pictures show the various public and private/loggedin states of the application, since we're planning to use the public app as primary target for links, the app offers in-app-switching to view personal data.

![ui-responsive-public-mode-no-sidebar](https://user-images.githubusercontent.com/1715840/76632720-f2dceb00-6543-11ea-81f5-6dd2bb73147e.png)

![ui-responsive-public-mode-opened-sidebar](https://user-images.githubusercontent.com/1715840/76632733-f7090880-6543-11ea-8ed3-ac29e4e401e7.png)

![ui-browser-private-mode](https://user-images.githubusercontent.com/1715840/76632742-fa03f900-6543-11ea-82bc-5ba1a8c86271.png)
