### ISSUE TITLE
Download of publication list not working in IE (and Edge?)

### ISSUE THREAD

**Issue by agnepagne** [KTH-Library/bibliomatrix#96]
Nothing happens on click at the "Publication data for ..." button in Microsoft Edge and Internet Explorer browsers.

**Comment by mskyttner** [comment]
Edge and IE doesn't support Data URI:s (for Excel documents anyhow) according to https://docs.microsoft.com/en-us/previous-versions//cc848897(v=vs.85)?redirectedfrom=MSDN

**Comment by agnepagne** [comment]
According to https://intra.kth.se/it/programvara-o-system/programvara/installera/programvara-i-kth-wi/paketerade-program/boff-support.html# KTH Windows computers now have "Microsoft Edge Chromium - UI" installled. This should work with Data URI:s, but would be great to have this comfirmed by someone using KTH Windows.

**Comment by fileunderwater** [comment]
Download seems to work now in Edge, so we close the issue
