### ISSUE TITLE
Add "Analysis unit" or similar above organization dropdown

### ISSUE THREAD

**Issue by fileunderwater** [KTH-Library/bibliomatrix#98]
To make the unit selection more prominant/clear a heading should be added above the dropdown menu to select organization unit/personal data

**Comment by fileunderwater** [comment]
Adding a quick fix to this in download_filenames branch (#97 )

**Comment by fileunderwater** [comment]
Closed by merge of #97

**Comment by mskyttner** [comment]
Slightly modified in #99
